import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faArrowRight,
  faStar,
  faBars,
  faShoppingCart,
  faCheck,
  faEnvelope,
  faPhone,
  faUser,
  faPalette,
  faImage,
  faCode,
  faPrint,
  faPaintBrush,
  faChartLine,
  faHashtag,
  faPoundSign,
  faHeart,
  faGlobe,
  faPlay,
  faBolt,
  faBuilding,
  faSchool,
  faUsers,
  faHospital,
  faComments
} from '@fortawesome/free-solid-svg-icons';

// Add icons to library for global use
library.add(
  faArrowRight,
  faStar,
  faBars,
  faShoppingCart,
  faCheck,
  faEnvelope,
  faPhone,
  faUser,
  faPalette,
  faImage,
  faCode,
  faPrint,
  faPaintBrush,
  faChartLine,
  faHashtag,
  faPoundSign,
  faHeart,
  faGlobe,
  faPlay,
  faBolt,
  faBuilding,
  faSchool,
  faUsers,
  faHospital,
  faComments
);

// Icon name mapping for consistent usage
export const ICONS = {
  arrowRight: faArrowRight,
  star: faStar,
  menu: faBars,
  cart: faShoppingCart,
  check: faCheck,
  email: faEnvelope,
  phone: faPhone,
  user: faUser,
  design: faPalette,
  image: faImage,
  code: faCode,
  print: faPrint,
  branding: faPaintBrush,
  analytics: faChartLine,
  hashtag: faHashtag,
  pound: faPoundSign,
  heart: faHeart,
  globe: faGlobe,
  play: faPlay,
  bolt: faBolt,
  building: faBuilding,
  school: faSchool,
  users: faUsers,
  hospital: faHospital,
  comments: faComments
} as const;

export type IconName = keyof typeof ICONS;
