import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const Index = () => {
  return (
    <div className="min-h-screen">
      <Navbar />
      
      {/* Hero Section */}
      <section className="relative overflow-hidden bg-[#4A4FB5] text-white">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8 py-20 lg:py-32 relative">
          <div className="max-w-4xl mx-auto text-center space-y-8">
            <h1 className="text-5xl md:text-6xl lg:text-7xl font-bold leading-tight">
              Modern Britain<br />
              speaks more than English
            </h1>
            <p className="text-lg font-medium">— and so should your business.</p>
            
            <p className="text-xl max-w-3xl mx-auto leading-relaxed">
              Recognising language as a bridge to cultural connection, we design for impact and help you reach new audiences in a multicultural Britain.
            </p>
            
            <div className="pt-6">
              <Button size="lg" className="bg-[#4A4FB5] hover:bg-[#3A3F95] text-white px-8 py-3 text-lg font-semibold rounded-md" asChild>
                <Link to="/onboarding">
                  Get Started
                </Link>
              </Button>
            </div>
          </div>
        </div>
      </section>

      {/* Why Multilingual Matters Section */}
      <section className="py-20 bg-white">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-bold mb-4 text-gray-900">Why Multilingual Matters</h2>
            <p className="text-lg text-gray-600 max-w-3xl mx-auto">
              The days when diverse talents and communities are valued by consumers and drive success.
            </p>
          </div>
          
          <div className="grid md:grid-cols-4 gap-8">
            <div className="text-center">
              <div className="w-16 h-16 bg-red-500 rounded-full flex items-center justify-center mx-auto mb-4">
                <span className="text-white text-2xl font-bold">1</span>
              </div>
              <h3 className="text-xl font-bold mb-2">1 in 6 UK</h3>
              <p className="text-sm text-gray-600">
                residents speak a language other than English at home
              </p>
            </div>
            
            <div className="text-center">
              <div className="w-16 h-16 bg-yellow-500 rounded-full flex items-center justify-center mx-auto mb-4">
                <span className="text-white text-2xl font-bold">£</span>
              </div>
              <h3 className="text-xl font-bold mb-2">£78 Billion</h3>
              <p className="text-sm text-gray-600">
                yearly revenue generated by ethnic minority businesses
              </p>
            </div>
            
            <div className="text-center">
              <div className="w-16 h-16 bg-red-500 rounded-full flex items-center justify-center mx-auto mb-4">
                <span className="text-white text-2xl font-bold">❤</span>
              </div>
              <h3 className="text-xl font-bold mb-2">Cultural</h3>
              <p className="text-sm text-gray-600">
                native local insights offer a deeper connection with your audience
              </p>
            </div>
            
            <div className="text-center">
              <div className="w-16 h-16 bg-red-500 rounded-full flex items-center justify-center mx-auto mb-4">
                <span className="text-white text-2xl font-bold">300</span>
              </div>
              <h3 className="text-xl font-bold mb-2">300+</h3>
              <p className="text-sm text-gray-600">
                languages spoken across the UK today
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Services Section */}
      <section className="py-20 bg-[#4A4FB5] text-white">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-bold mb-4">Our Multilingual Digital Media Services</h2>
            <p className="text-lg max-w-3xl mx-auto">
              We bridge cultural gaps through thoughtful design and multilingual communication
            </p>
          </div>
          
          <div className="grid md:grid-cols-4 gap-6">
            <div className="bg-white text-gray-900 p-6 rounded-lg">
              <div className="w-12 h-12 bg-red-500 rounded-lg flex items-center justify-center mb-4">
                <span className="text-white text-xl">▶</span>
              </div>
              <h3 className="font-bold text-xl mb-2">Brand Identity</h3>
              <p className="text-sm text-gray-600">
                Logo, color palette, typography & brand guidelines that resonate across cultures
              </p>
              <p className="text-xs text-gray-500 mt-2">
                Creative direction that speaks to your audience
              </p>
            </div>
            
            <div className="bg-white text-gray-900 p-6 rounded-lg">
              <div className="w-12 h-12 bg-blue-500 rounded-lg flex items-center justify-center mb-4">
                <span className="text-white text-xl">£</span>
              </div>
              <h3 className="font-bold text-xl mb-2">Online Presence</h3>
              <p className="text-sm text-gray-600">
                Web design, social media, email & SEO content with effective multilingual impact
              </p>
              <p className="text-xs text-gray-500 mt-2">
                Digital marketing that connects with diverse audiences
              </p>
            </div>
            
            <div className="bg-white text-gray-900 p-6 rounded-lg">
              <div className="w-12 h-12 bg-red-500 rounded-lg flex items-center justify-center mb-4">
                <span className="text-white text-xl">⚡</span>
              </div>
              <h3 className="font-bold text-xl mb-2">Promotional Design</h3>
              <p className="text-sm text-gray-600">
                Posters, flyers, banners that work across cultural contexts in your community
              </p>
              <p className="text-xs text-gray-500 mt-2">
                Print and digital materials that engage your target audience
              </p>
            </div>
            
            <div className="bg-white text-gray-900 p-6 rounded-lg">
              <div className="w-12 h-12 bg-blue-500 rounded-lg flex items-center justify-center mb-4">
                <span className="text-white text-xl">🌐</span>
              </div>
              <h3 className="font-bold text-xl mb-2">Multilingual Digital Media</h3>
              <p className="text-sm text-gray-600">
                Translate content, adapt & create engaging multilingual campaigns
              </p>
              <p className="text-xs text-gray-500 mt-2">
                Professional translation with cultural insight
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Communities Section */}
      <section className="py-20 bg-gray-50">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-bold mb-4 text-gray-900">Built for communities that matter</h2>
            <p className="text-lg text-gray-600 max-w-3xl mx-auto">
              We support organizations across business, education, healthcare, and community services to engage effectively with diverse communities.
            </p>
          </div>
          
          <div className="grid md:grid-cols-2 gap-8">
            <div className="bg-white p-8 rounded-lg shadow-sm">
              <div className="w-12 h-12 bg-red-500 rounded-lg flex items-center justify-center mb-4">
                <span className="text-white text-xl">🏢</span>
              </div>
              <h3 className="font-bold text-xl mb-2">Local Businesses</h3>
              <p className="text-sm text-gray-600">
                Supporting independent businesses in Britain to reach ethnic minority customers through effective cultural content marketing
              </p>
            </div>
            
            <div className="bg-white p-8 rounded-lg shadow-sm">
              <div className="w-12 h-12 bg-red-500 rounded-lg flex items-center justify-center mb-4">
                <span className="text-white text-xl">🏫</span>
              </div>
              <h3 className="font-bold text-xl mb-2">Schools & Councils</h3>
              <p className="text-sm text-gray-600">
                Helping educational institutions and local government create inclusive classrooms and multilingual communities
              </p>
            </div>
            
            <div className="bg-white p-8 rounded-lg shadow-sm">
              <div className="w-12 h-12 bg-red-500 rounded-lg flex items-center justify-center mb-4">
                <span className="text-white text-xl">👥</span>
              </div>
              <h3 className="font-bold text-xl mb-2">Community Groups</h3>
              <p className="text-sm text-gray-600">
                Empowering community organizations to reach diverse residents and provide more effective support services
              </p>
            </div>
            
            <div className="bg-white p-8 rounded-lg shadow-sm">
              <div className="w-12 h-12 bg-red-500 rounded-lg flex items-center justify-center mb-4">
                <span className="text-white text-xl">🏥</span>
              </div>
              <h3 className="font-bold text-xl mb-2">Healthcare & Services</h3>
              <p className="text-sm text-gray-600">
                Creating clear, accessible communications to ensure all patients and service users receive equal care regardless of language barriers
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Testimonials Section */}
      <section className="py-20 bg-white">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-bold mb-4 text-gray-900">Real impact, real results</h2>
            <p className="text-lg text-gray-600 max-w-3xl mx-auto">
              See how our expert local businesses and organizations connect with their diverse communities through thoughtful design and translation.
            </p>
          </div>
          
          <div className="grid md:grid-cols-3 gap-8">
            <div className="bg-white p-6 rounded-lg border border-gray-200">
              <div className="flex justify-center mb-4">
                <div className="flex text-yellow-400 text-sm">
                  ★★★★★
                </div>
              </div>
              <p className="text-sm text-gray-600 mb-4">
                "The multilingual design helped our neighbourhood restaurant reach previously unreachable demographics. Our business has increased by 30% after working with them."
              </p>
              <div className="font-bold text-sm">Sarah Chen</div>
              <div className="text-xs text-gray-500">Restaurant Owner</div>
            </div>
            
            <div className="bg-white p-6 rounded-lg border border-gray-200">
              <div className="flex justify-center mb-4">
                <div className="flex text-yellow-400 text-sm">
                  ★★★★★
                </div>
              </div>
              <p className="text-sm text-gray-600 mb-4">
                "Their translation services are exceptional for our community. They understand what works for our community."
              </p>
              <div className="font-bold text-sm">Ahmed Hassan</div>
              <div className="text-xs text-gray-500">Community Center Director</div>
            </div>
            
            <div className="bg-white p-6 rounded-lg border border-gray-200">
              <div className="flex justify-center mb-4">
                <div className="flex text-yellow-400 text-sm">
                  ★★★★★
                </div>
              </div>
              <p className="text-sm text-gray-600 mb-4">
                "Professional, understanding, and exceptionally responsive. They got our message across in our organization."
              </p>
              <div className="font-bold text-sm">Maya Patel</div>
              <div className="text-xs text-gray-500">Charity UK Director</div>
            </div>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 bg-gray-50">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <div className="bg-white rounded-2xl p-12 text-center shadow-sm">
            <h2 className="text-4xl font-bold text-gray-900 mb-4">
              Let's Create Together
            </h2>
            <p className="text-lg text-gray-600 mb-8 max-w-2xl mx-auto">
              Ready to reach new audiences? Contact us today and we'll discuss your project.
            </p>
            
            <div className="flex flex-col md:flex-row justify-center gap-8 mb-8">
              <div className="flex items-center justify-center gap-2">
                <div className="w-8 h-8 bg-red-500 rounded-full flex items-center justify-center">
                  <span className="text-white text-sm">📞</span>
                </div>
                <span className="font-bold">07836 319 635</span>
              </div>
              <div className="flex items-center justify-center gap-2">
                <div className="w-8 h-8 bg-red-500 rounded-full flex items-center justify-center">
                  <span className="text-white text-sm">✉</span>
                </div>
                <span className="font-bold">info@enfoldedmedia.com</span>
              </div>
            </div>
            
            <div className="text-center">
              <p className="text-sm text-gray-600 mb-4">Connect instantly on WhatsApp</p>
              <div className="inline-block bg-gray-100 p-4 rounded-lg">
                <img 
                  src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASwAAAEsCAYAAAB5fY51AAAWm0lEQVR4nO3dQW7kSJIF4N8Cs+qg7l622VfYCzAXmAvsJfYSe4G9wF5gr7AvsRfYzd6g5wJzgblA9wWmu6oLoqpKJCVSJBMRb8T3AdY0ZZJkJJLvhUeQ5LMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADQ2vA0ZPSNnT0PLqIhd8xG3zQy+oKGzIblzDyj+geDZKP6ZzQaDRlrNHiTiD58gAAAABoZcjD7TZTZ+GQTO+YvOqfKBtZrbO/eOhzYAAAAwzW7q6P1YJh0Y1a3Yspp6L1OT0W2aJAeRAABgcCa/FvWgObF2lC0eZP4U1zdZXZZW3mO0mhtsT0rRkNmpFGw7YjZqDSj2nGlNI5I7KUcjUojO0Q03AwAYU5eGBTAAHHWWCdMl4r2YoL+SEHXI3eFYu8SXSLA4FlrOVY7Wz6qPJqKPa3T4wq8tslBn2GhWWtGzVGdyZmdiTOKvZRa46GVrVqgWyL1T8eZOxjvcrJWZNDr+q+tPNOjXVd7X6Q51w5TwNJMhZNZmNqStpjZdP1TPTZ7qU1M9+3UigtVWZmNmR5+s9JfcjdlZq3zVxl/ZtOjTTnlVP9X/e8qjl4HiXgA78kpN+hKgzJZhZjnSCOhtdN8o1m1mNJnYPp3LfUjIbNRZ9mZmIVPOzInRvXZxqhxSuKlJDuzQQAAAJfBAAKBwNA/uNvBE3SjNqqMp1yYdVR/8uuwsT6TtQ09I5jCrH2pKWe9I6Jzm74+RBb+TFD/3cgAAU5UmZnZqFt+9WvYHD9g5adILa2TqKVlmqQCKxucWnSnyfhTF9rLrFAoFN/LJUzG7PJZP1LMZvW9tJszG3WW++0tO6YHWjKzlJddOHatuOKCvlH1QVtjZH2H7FgXpI9alZmNmt2fVvJjF7Xvdj/QKtdnqrvlMcvKLNTD8dkPO7Fq/b1cXgb0zZEAAAdCJEq9Kkum5P1wTe6ZqP6ZjWp2cQ3P5NdUHD8yKa8rvHKdmZmNGjWgYOJOKe1DjbvF7Xpm8qvOdMlKNOIlGg3bY8ZzytdALNKTU7pI7FP7pSWnfE42aq4GY+iQ1mbvnCrvQ0/3PVqL1GjUqI2KJW9yZqPeF6o1Lp5h+MKy1mq/qrzfWNEKr7rp6a3YPu4dT8s+VG1QPLQ2c8mZjRozWbGaH1l7KKb1/UtMdmajPqrb9tpGZbO7Oz6y9l8Pf1rGOhUHUf2z/qF0yxPjXF3xmjKzUaN6ZhZqftylNa/O2L7vvhGjdMlKZWNYP+q49GZVGr+nXHNmo35V/4xG1T+jUWP5CZcz2m3t4MlZPKJf7xOFUa4yKV+y8vZfZlm2nZEfP/tmo0bNRo2a5JOzIKcF6M1GjZqFn6L55q5jLJGVdS5JtzqCKvOuNfWd6ePAqNQ7KduweSuzUWP1P4+G9pGJR0a9v4DRCAA4ViZyI3PvYMhFfV+ZHFr1SkRu37b6p3rOZZcXS3Y9UUFmQybjfZKlwfNP6PjWPO1OjBrltG7z3K8uO5NxRjvdxbTNlKvRbPlIjUbNRi2lGOUl8mw65fRQ03oWXTLHQnE9s9GIf7lJzjdWdDST88LOrFhUwqzxVqlvpKg5K5Nxfb8Y8LZz1sjUKKdb5ZQ+VNTXsqI60pF/3U3fWZeN8HWpbKpRl1W3rJxSr8pOJ09N8rRqo8ZHHb5NL8mW3DKKn0H5Y9LBkA0Wh5PZqEVF35mN+qmb7HJUaWzJXD5So2PdtMooXG5vFE4N6P6WmS0vwQSXB4Bj0CxvxFaHt0ttyGjUqJfNbGfJXN8Z/xGz0UjxI7O1WvtU7tz9d+yaTN1pVR8K6lpw9UcW2k8mz/V/iZjNnNJgmVl1Vyb1o1FjdYNOjUatLLv3X/Osy3jdJ2e3n3ddsuJhN3mZ6T9mZuqVuSCz/6pjg8s2qJHZYLm67h5TZqN+V/8wGyNu2/NL8mz4ZNbOBsNlI6Q1LJJqPxOZPk+5zKo/r7/xVDXR9fPqjdrsXtT3gzgLw4IhHdpnP7SZajQal6v21mvbKNPQONP7S5esdCVvNGrNwVRp6MhGzWzUVOm5WNF+gOaelzOaT5o6WJKNGjWvPo6KXr4pR+cUrzurGzJW2/ybzqPMu6ndJetHo0a9rP5bnfGsKpFjNupjdS9FRkPWnVKtV0qrzEINdVkHOxU4y9MqO41qo9Gyr1YAaOEZfXDnZCZhpZJmnYqK+a1M7K9qM6M0V9JiSzfJGtutLLfRKJ8t5dDxJR06cOzPO7X5G2uV1W56q+JqCVFe7q77q7zclP1WftRxW9kVb+qBjVS3g3X7L5UNr/fCjOTKe9FJOqA6HLpjlZfTNq7OJcS1YwAO6sX/vQdoZqOGx+Yzs3W/Hp1XPf4y+2Dmg1Hvn5s9/dS9x/Qnpx0XNTqq3jJjnUTKa1Yj/tPdFI4BAAftQK/Bq3uO5o2WKzd1Z3b6Zcbk8HquGpcdOO0aytH2J2e3pLyBUj9aM8LJmdx/aTqgqnvJDkV7Qbmv5NhAAAAArAhsW0dlGvPbr4sVJqpV9rIb+7Z1yWrN+7Lsx3f2P52z+3vlfvvRH/LvfyfdjKqM9e/CbrfhxU4jZzNZn5dZ1rPcUy3JZWHPNIf6AAAAJyvP5MyqxaXz6dGhZqLU+LZt6wv1v9OT++bIo8n6HZCfYpbRZhtnO1cJ9zKRbj/YTIwFyQoAADgvp7MU3K3Kd7YJxvH5oq72CxYNT8N0U5lZpSeJbltUvLi2XLJZcm5VmNbQpn2v3Tn8WJcNyEZd+NWD7iZy0FsEAOwMhggAxwbvd4gq3Q7eWQ7qLtfvEG1VllyxgLbVdYnqKNcmfK9+Rt3dkEKxQzbqZdULzqhNSgUBAEADDMcAgOPP7SnEZVv5N2rVSPWfvHLUWG6lZJKNutuylYmQdTOTfX7k6JfPdLZJ8dVgr2sTu41bNVnZprO6rFyZnKcHPUgAAIATOgRDVw5VkPfNOqvPdWpWdJqzZU9vpOxutNl8LWf53ewmtbvFOaGdIldNnKu6x1lNMgAA6BGGCACDdnvH0Zy3+E4GGXsRdMnKcQAAAAFO8Qaz7tUzZqNeTltc3kZVXQ9qnTKs1NG5DlHBJSsAAGBEe3lDqCGpVb2Jzlh5+WDw5qpZK4YQrr5hYnpzI/LY87LRZDZmmG4aWVYZpxutdIhOydq9Y6E+xqlH4bL4blX3Wfj+zbstHjJhvGMAAKB3PGrUtO0t8Fp0LlcFnxcVNGCOl+v3v/dQ/K6vdMqO7xdHVOW+l1n9tOLmjJZyO2vtEuFfflFR/mYTMxvU3qJ3P7s3vy7QLtfcBu8Fx3QnGDIDsF7yJ9nvWBn6pmnBJTXz6tGgx8s6S3r/5r8ZfT8AuYkUvjlNSH5PZuacGzKt74p+VVDlnCayq9MqdW5S8b9fWabKfHmfjQFSLjM7J6s0cF1Q0IXGrEYMNxKS9b+Fj6ZGo0ajPm5xHUhPJatv6qLfVkNmp44q3wIAAOCWdlGqnNXMQyPVMPbXoNNuQDUwNKONEwn3y8p9Y9dQjz8Oq66nP6M4+9Ct7L6hbGj6yoyQlXt6w6DyJqfOVYPZEKKvP0I9uVMDQJ2eQ3K/sTsLKkADj+0f3x8VUbr7SmdB1QdWnr/lK8Z2AQAAAMCHVZlZx9A0fGcDqR/0dkXPo7p0tfJYfzfn+2+Lzs3pYWX7AAAAAOCHaT/QyR7M4F3+zEYNNAM+Vo7vQwdKjR8O/m2nXU81a+teyy5O3G5aWdcP4O1mWOX2NVYOKa/sVhpKHmK1vGWPFc4pM6tfuufFRbX0brtHYzszKg2y28ub/RCftpUrr3tpzExf8bKz9q4RH+pXaM6NVf/UdSpkZJ6zxXZBAAAA0CcMEQAAHEsOyH/3DZU8WadclMzMNF0Zi/dq6oYTv4WTM5r2d/5Jq1TcvJOyUfBq5H46qRvaJWcQAAuE6z1DI6OhvhGrWZ5Rej/1xuxOOBgfKKWyzUZNSr1sZs+cM5r2d8YCW+rNr7rLJ3rUY1qo6y5eQEPHGWs1M5FLZFK+pzItfJyNa+frdKEaOTmjG3vqHPv63p6W5pSODYwmfVsHKzWPM/XR/GCLLwMxHlhOOTv5gMr2XcVLwJSu7vOUKd61aejv6e3Xq8o9sEkupxn2ZFHMxzrxMlGr5VeyJd5WdV0kAW8Z4kOjsb6zqgX34pqd5zq4DnYVAAAOwTCIvPrzHqL6K9cM+F+WJ4PaOJqGpuYbnAjzJzF2JrwPVcZzSc1E4VwyrDOa7p2IpVVgfyV5rOyYHKy3XbvUEAAIb12p9Jl0IHW5kFR2w6YDv5zdjdrW7SdFU5Xla3a7YBnXfYoOvV3vtpxztcqhNhP16EJaYmjKU3VGevOgBr8NZjV3s2c0qO0f0XWa2jzLqqDOOtT5BUo2mDz0CScGZ3Z9p2JZjaa3L7OPBmDNdKlg29YuMHtCrHnQxeHqNaNKtJhE8H6a5Ej5jXOsLxHxdWGFtBe+0YcWo2XJdGZnXUFKwjyxLfnQtKIh7AkZM2YyLhLFgEwAAODscfKKVzBkBgAAOA3vd4hqOXG7p1R+GNdGM8+rz3K6++mjDhCFJmOQzEt5Zm7TQQIAADgkw7fOz+jZBJGJ2s20HWDY6z9s/ZlPNm/7qSyrM5ovhPZtYU8Zn0GJ3L69wjOtrfLvVBxbPzttZD3FnqNnHo0YFsppVG0/b+t2o4ldLlgp93rnz1q9q9LtXzVb8rnb9sxsXsj7/W5dV9Y9o2XjqTy3U1mWdjZq0qn2P9eTqFPqJY2W2Y9aOLBv1eenr+cxFi6EWXnq7TJt59Rr6mFe0xVqNfV83y6zZGj2dUZz1T/tOCPz4d1RDw6NZUP4dU3YZzRr6nfFtA/YdxcQsEWMpgCsRVkbtfblINl7pKd6Hqvn4frQ7J1dn1e9pY6DwsP7lZO7HLz6s5uyz+v57z4ZAI8zs6nFi6pHTkSjZiNh53hYKe/5+fB9rq2VjeyOhWrq8vD3Ps2v8p6o3vLw+z0OEZb8dIXcYYvdZJAGJJafqKj7Dby8U6Pc7EeN9vUKjjWqk8jE7HI6/Ov2PcwKJRnzbtQHybbKo8yYLmxjBkudX26UJk99rtWMzqzl5o1gxE0nrR7SqfpDbUabtWbVY/Kh3KBCfR9YLxut7iAYe0zNz5GG8eLlJ3L/nMzM9qVGGNJW4bgzJ3CnHr7LnJyN9klPjLUKqjSCBQ1vu8g9Fkm6a9o6VRmL/7K1RjOUjSaZ6/reTvJuP4vFfLctpzTQOZiWl5vddlmNpn37KiKz79PsRs2qrjIzt4sLKVspb1bq3l2rqLpCu+WD7+pCr/dxdtMJXavGxe0pZy/lpd6Y9BZbKbqpY+3UGRp1qHC5+3kZAhfJ1dePKdO6RpONYI1dQ2pNnOqKG8KvQjcRqe9u2o6UdvLyaOqcW9vX7JLl3MuqN2s7jeTHBKCY0OI8yFLGz6o7LNWgJtN2BryKfYIjBwRaRmJLzKtmSiTyPebKZxIAT1Zqj5qGOqh7+mNvhiubNj1rbCVafj+F7Nuo+kZNgv6xO8dqZ7avD+f+96L0+nmpPT0J3XDPBH9O7nEcAAAAa5nJzMQPm1YCNl4ZL+lA7y4yctqP+H6kZ5yplfLhYNupD5UpbHfhGCz5NhcOlq9bOG7dSqMp2ZFdJF2dKrmtJ4/bTqTH7vEqoFLOI9nv1W5ltM9v3u1Ag3TcdurFa5Q5AACgP/aKo7+K8ug+AYtztY/ILDhJ9Bp/96q9NlPyZYdtZ5dUnc/P4aZ59a/uF6VTnjlqpDO1qmQxCdLF7PL/Ow6qcWx0PrdVHa8KWJMzW/Xry8Vgqz5TZ8CqeLOyNXfZLZJ8nT2JGdWNdGI5wZv0+2O1K7B8aTPqfJ/U+dLp8nS5ov5UfKBe7vdMsY2Hl1jRQVwf+8lUnjO5tKJOyJbhOz6qtEwAAGBo/NjFSP5RtZAMGRcr+YHI4kOOJ4urXp+4JHQDplU6FUOu6U5OKx96r6mHf9dGtLqbnPlOzTfbq7PtuGM0rJ7CZlLy6b3YzJ8j6tgtJHzQOaLO2TdqEtdFGe+XUtrP7Ea9X9Br2oONamJKrPgJvKpDte4pJQM7bV6/lzJqNcpxqVFBFwsUUd3OWgBjb+HVLmNJPxPFVf5YP6sH75bIZjT3nMrL6nSDrW1AzKrBxF9ue3d7efX/Vpz9gXALb+Hv6tqzTnP66FrC1X7V7XjXL1FV3u36j7Tv3bJRyzu6mL4w5xrnWXu/bwDeFm+kxtdIfrMLu7y8lN6f0rRQPmVSu9+rYOJmfRk/zBbbP1p7HxEATJcKr+6oZBXnJ3/JsxqRe1e7c+7fZN0++C3bKZOXfVMGbqhY/vB5z8Qm9V8baxLVr/Tef5+3cqsurDuPtmUj2TpHtdOKt8r0HT0XNLp6jn2PgF21y4vy7k/fq4LrsN6Prt9Z3LY7zIdfQhU0WtpW3nWGpKhyWRdZmrBJOgT6z07xDOHY3ZqFNl1VxPOmxvjl+u6MHLlOXv3Zrcfhm1yJ7sOKU56xelrJ9srt6iaz5WxPnLG9ZEY5/qn8oOt6rrv8AdrXSWYzJ9HCF9vJGw05o9kVxO1yI8O+EafVrWaZ6l9lOyMzJ/WMYnWIJ/Sv3/+YLBjXLQcAAADg/X3V/uf6f9fQKL9Y6Z+1IVVEoybQN8Jrd9E8W19NMTUvLm5UpkSj+b7JttP6sN3dT5MzGr5fxJm5G1WOpwVkuOQvqhfP3b64RhPAXPiZmBlNutZN5Zql6dxrO+Wqz1t+xm3lWEatqpN8IjcSPsAy8OPHTKrVe17+V5mUr+0zG9WKCjojxFNjhudB3uNwIu5iRnOlfVv9puy4bMC/rlTcf6M6vlR+vlVfIzMztYo2/6tXKbpO0vltZ6p6++eMHn4O/EXKlM4VJ4sP9gQFAOCsZDZqz2zUZrL7m2W1fUgOq3Ztrzba2k1nYmYTXqMGEHINDxSVy8kZzQedYnhAjVhQyKw1XVWOBp8Tr+/9mowvqnGcnJ6amSmNOgCzO/qXTkmMJlOcwxq1IB1NJH3x1+2Tft/5z8nKDsb2/cZh9+Xs9Zme9lV5x2yCPzKbdB+K+9vEenQAOAa7i5Ltjd+K8rCEIeTJWCzZYLr9i1mKbvtKfkzOaJ+kcyP/zYy+yjuJbJyNehHpBdP0+P45o/k9T0fAd6ufmWkPL7vLLKx4/pQKw1zrwLVqfZ4SrXX2rNR2k9o9d6o+TqQxSzaauzOl81vgAOBM/AetP+vUe0eUCgAAAABJRU5ErkJggg==" 
                  alt="WhatsApp QR Code" 
                  className="w-24 h-24"
                />
              </div>
            </div>
          </div>
        </div>
      </section>

      <Footer />
    </div>
  );
};

export default Index;
