import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const Index = () => {
  return (
    <div className="min-h-screen">
      <Navbar />
      
      {/* Hero Section */}
      <section className="relative overflow-hidden bg-[#4A4FB5] text-white">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8 py-20 lg:py-32 relative">
          <div className="max-w-4xl mx-auto text-center space-y-8">
            <h1 className="hero-title">
              Modern Britain speaks more than English. Your business should too.
            </h1>

            <p className="lead-paragraph mt-3">
              We design for impact, recognising language as the bridge to cultural connection that helps you reach new audiences.
            </p>

            <div className="h-4" />

            <p className="hero-sub mt-2">
              Browse our Packages or get in touch for something custom.
            </p>
            
            <div className="pt-6">
              <Button size="lg" className="bg-[#4A4FB5] hover:bg-[#3A3F95] text-white px-8 py-3 text-lg font-semibold rounded-md" asChild>
                <Link to="/packages">
                  View Packages
                </Link>
              </Button>
            </div>
            <div className="mt-3">
              <a href="#contact" className="text-sm text-white/80">Or email us to discuss a custom project</a>
            </div>
          </div>
        </div>
      </section>

      {/* Why Multilingual Matters Section */}
      <section className="py-20 bg-white">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="section-title mb-4">Why Multilingual Matters</h2>
            <p className="text-lg text-gray-600 max-w-3xl mx-auto">
              The days when diverse talents and communities are valued by consumers and drive success.
            </p>
          </div>
          
          <div className="grid md:grid-cols-4 gap-8">
            <div className="text-center">
              <div className="w-16 h-16 bg-red-500 rounded-full flex items-center justify-center mx-auto mb-4">
                <span className="text-white text-2xl font-bold">1</span>
              </div>
              <h3 className="text-xl font-bold mb-2">1 in 6 UK</h3>
              <p className="text-sm text-gray-600">
                residents speak a language other than English at home
              </p>
            </div>
            
            <div className="text-center">
              <div className="w-16 h-16 bg-yellow-500 rounded-full flex items-center justify-center mx-auto mb-4">
                <span className="text-white text-2xl font-bold">£</span>
              </div>
              <h3 className="text-xl font-bold mb-2">£78 Billion</h3>
              <p className="text-sm text-gray-600">
                yearly revenue generated by ethnic minority businesses
              </p>
            </div>
            
            <div className="text-center">
              <div className="w-16 h-16 bg-red-500 rounded-full flex items-center justify-center mx-auto mb-4">
                <span className="text-white text-2xl font-bold">❤</span>
              </div>
              <h3 className="text-xl font-bold mb-2">Cultural</h3>
              <p className="text-sm text-gray-600">
                native local insights offer a deeper connection with your audience
              </p>
            </div>
            
            <div className="text-center">
              <div className="w-16 h-16 bg-red-500 rounded-full flex items-center justify-center mx-auto mb-4">
                <span className="text-white text-2xl font-bold">300</span>
              </div>
              <h3 className="text-xl font-bold mb-2">300+</h3>
              <p className="text-sm text-gray-600">
                languages spoken across the UK today
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Services Section */}
      <section className="py-20 bg-[#4A4FB5] text-white">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="section-title mb-4">Our Multilingual Digital Media Services</h2>
            <p className="text-lg max-w-3xl mx-auto">
              We bridge cultural gaps through thoughtful design and multilingual communication
            </p>
          </div>
          
          <div className="grid md:grid-cols-4 gap-6">
            <div className="bg-white text-gray-900 p-6 rounded-lg">
              <div className="w-12 h-12 bg-red-500 rounded-lg flex items-center justify-center mb-4">
                <span className="text-white text-xl">▶</span>
              </div>
              <h3 className="font-bold text-xl mb-2">Brand Identity</h3>
              <p className="text-sm text-gray-600">
                Logo, color palette, typography & brand guidelines that resonate across cultures
              </p>
              <p className="text-xs text-gray-500 mt-2">
                Creative direction that speaks to your audience
              </p>
            </div>
            
            <div className="bg-white text-gray-900 p-6 rounded-lg">
              <div className="w-12 h-12 bg-blue-500 rounded-lg flex items-center justify-center mb-4">
                <span className="text-white text-xl">£</span>
              </div>
              <h3 className="font-bold text-xl mb-2">Online Presence</h3>
              <p className="text-sm text-gray-600">
                Web design, social media, email & SEO content with effective multilingual impact
              </p>
              <p className="text-xs text-gray-500 mt-2">
                Digital marketing that connects with diverse audiences
              </p>
            </div>
            
            <div className="bg-white text-gray-900 p-6 rounded-lg">
              <div className="w-12 h-12 bg-red-500 rounded-lg flex items-center justify-center mb-4">
                <span className="text-white text-xl">⚡</span>
              </div>
              <h3 className="font-bold text-xl mb-2">Promotional Design</h3>
              <p className="text-sm text-gray-600">
                Posters, flyers, banners that work across cultural contexts in your community
              </p>
              <p className="text-xs text-gray-500 mt-2">
                Print and digital materials that engage your target audience
              </p>
            </div>
            
            <div className="bg-white text-gray-900 p-6 rounded-lg">
              <div className="w-12 h-12 bg-blue-500 rounded-lg flex items-center justify-center mb-4">
                <span className="text-white text-xl">🌐</span>
              </div>
              <h3 className="font-bold text-xl mb-2">Multilingual Digital Media</h3>
              <p className="text-sm text-gray-600">
                Translate content, adapt & create engaging multilingual campaigns
              </p>
              <p className="text-xs text-gray-500 mt-2">
                Professional translation with cultural insight
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Communities Section */}
      <section className="py-20 bg-gray-50">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="section-title mb-4">Built for communities that matter</h2>
            <p className="text-lg text-gray-600 max-w-3xl mx-auto">
              We support organizations across business, education, healthcare, and community services to engage effectively with diverse communities.
            </p>
          </div>
          
          <div className="grid md:grid-cols-2 gap-8">
            <div className="bg-white p-8 rounded-lg shadow-sm">
              <div className="w-12 h-12 bg-red-500 rounded-lg flex items-center justify-center mb-4">
                <span className="text-white text-xl">🏢</span>
              </div>
              <h3 className="font-bold text-xl mb-2">Local Businesses</h3>
              <p className="text-sm text-gray-600">
                Supporting independent businesses in Britain to reach ethnic minority customers through effective cultural content marketing
              </p>
            </div>
            
            <div className="bg-white p-8 rounded-lg shadow-sm">
              <div className="w-12 h-12 bg-red-500 rounded-lg flex items-center justify-center mb-4">
                <span className="text-white text-xl">🏫</span>
              </div>
              <h3 className="font-bold text-xl mb-2">Schools & Councils</h3>
              <p className="text-sm text-gray-600">
                Helping educational institutions and local government create inclusive classrooms and multilingual communities
              </p>
            </div>
            
            <div className="bg-white p-8 rounded-lg shadow-sm">
              <div className="w-12 h-12 bg-red-500 rounded-lg flex items-center justify-center mb-4">
                <span className="text-white text-xl">👥</span>
              </div>
              <h3 className="font-bold text-xl mb-2">Community Groups</h3>
              <p className="text-sm text-gray-600">
                Empowering community organizations to reach diverse residents and provide more effective support services
              </p>
            </div>
            
            <div className="bg-white p-8 rounded-lg shadow-sm">
              <div className="w-12 h-12 bg-red-500 rounded-lg flex items-center justify-center mb-4">
                <span className="text-white text-xl">🏥</span>
              </div>
              <h3 className="font-bold text-xl mb-2">Healthcare & Services</h3>
              <p className="text-sm text-gray-600">
                Creating clear, accessible communications to ensure all patients and service users receive equal care regardless of language barriers
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Testimonials Section */}
      <section className="py-20 bg-white">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-bold mb-4 text-gray-900">Real impact, real results</h2>
            <p className="text-lg text-gray-600 max-w-3xl mx-auto">
              See how our expert local businesses and organizations connect with their diverse communities through thoughtful design and translation.
            </p>
          </div>
          
          <div className="grid md:grid-cols-3 gap-8">
            <div className="bg-white p-6 rounded-lg border border-gray-200">
              <div className="flex justify-center mb-4">
                <div className="flex text-yellow-400 text-sm">
                  ★★★★★
                </div>
              </div>
              <p className="text-sm text-gray-600 mb-4">
                "The multilingual design helped our neighbourhood restaurant reach previously unreachable demographics. Our business has increased by 30% after working with them."
              </p>
              <div className="font-bold text-sm">Sarah Chen</div>
              <div className="text-xs text-gray-500">Restaurant Owner</div>
            </div>
            
            <div className="bg-white p-6 rounded-lg border border-gray-200">
              <div className="flex justify-center mb-4">
                <div className="flex text-yellow-400 text-sm">
                  ★★★★★
                </div>
              </div>
              <p className="text-sm text-gray-600 mb-4">
                "Their translation services are exceptional for our community. They understand what works for our community."
              </p>
              <div className="font-bold text-sm">Ahmed Hassan</div>
              <div className="text-xs text-gray-500">Community Center Director</div>
            </div>
            
            <div className="bg-white p-6 rounded-lg border border-gray-200">
              <div className="flex justify-center mb-4">
                <div className="flex text-yellow-400 text-sm">
                  ★★★★★
                </div>
              </div>
              <p className="text-sm text-gray-600 mb-4">
                "Professional, understanding, and exceptionally responsive. They got our message across in our organization."
              </p>
              <div className="font-bold text-sm">Maya Patel</div>
              <div className="text-xs text-gray-500">Charity UK Director</div>
            </div>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 bg-gray-50">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <div className="bg-white rounded-2xl p-12 text-center shadow-sm">
            <h2 className="text-4xl font-bold text-gray-900 mb-4">
              Let's Create Together
            </h2>
            <p className="text-lg text-gray-600 mb-8 max-w-2xl mx-auto">
              Ready to reach new audiences? Contact us today and we'll discuss your project.
            </p>
            
            <div className="flex flex-col md:flex-row justify-center gap-8 mb-8">
              <div className="flex items-center justify-center gap-2">
                <div className="w-8 h-8 bg-red-500 rounded-full flex items-center justify-center">
                  <span className="text-white text-sm">📞</span>
                </div>
                <span className="font-bold">07836 319 635</span>
              </div>
              <div className="flex items-center justify-center gap-2">
                <div className="w-8 h-8 bg-red-500 rounded-full flex items-center justify-center">
                  <span className="text-white text-sm">✉</span>
                </div>
                <span className="font-bold">info@enfoldedmedia.com</span>
              </div>
            </div>
            
            <div className="text-center">
              <p className="text-sm text-gray-600 mb-4">Connect instantly on WhatsApp</p>
              <div className="inline-block rounded-lg overflow-hidden">
                <img
                  src="/assets/qr.png"
                  alt="WhatsApp QR Code"
                  className="w-32 h-32 rounded-md"
                />
              </div>
            </div>
          </div>
        </div>
      </section>

      <Footer />
    </div>
  );
};

export default Index;
